import type { CalendarEvent, EventAttendee } from "@/types/calendar.types";

function pad(n: number) {
  return n.toString().padStart(2, "0");
}

/** Build an ISO datetime for "today + dayOffset" at the given hour/minute. */
function at(dayOffset: number, hour: number, minute = 0) {
  const d = new Date();
  d.setDate(d.getDate() + dayOffset);
  d.setHours(hour, minute, 0, 0);
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(hour)}:${pad(minute)}:00`;
}

const team: EventAttendee[] = [
  { id: "u1", name: "Maya Chen", avatarColor: "#7C6CF6" },
  { id: "u2", name: "Rohan Iyer", avatarColor: "#FF8B6B" },
  { id: "u3", name: "Priya Nair", avatarColor: "#6FCF97" },
];

/**
 * Deterministic mock dataset spanning last week through next few weeks,
 * so Month/Week/Day/Agenda views all have believable content out of the box.
 */
export function buildMockEvents(): CalendarEvent[] {
  const events: CalendarEvent[] = [
    // ---- Today's timeline (Section 4 reference schedule) ----
    {
      id: "e-today-1",
      title: "Morning Workout",
      description: "Strength training — legs and core.",
      type: "workout",
      category: "Health",
      priority: "medium",
      status: "completed",
      location: "Home gym",
      startDate: at(0, 8, 0),
      endDate: at(0, 8, 45),
      allDay: false,
      color: "#6FCF97",
      icon: "Dumbbell",
      completed: true,
      source: "habit",
    },
    {
      id: "e-today-2",
      title: "Team Standup",
      description: "Daily sync with the product squad.",
      type: "meeting",
      category: "Work",
      priority: "medium",
      status: "completed",
      location: "Zoom",
      startDate: at(0, 9, 30),
      endDate: at(0, 9, 50),
      allDay: false,
      attendees: team,
      color: "#7C6CF6",
      icon: "Users",
      completed: true,
      source: "manual",
    },
    {
      id: "e-today-3",
      title: "Lunch",
      type: "personal",
      category: "Personal",
      priority: "low",
      status: "upcoming",
      startDate: at(0, 12, 30),
      endDate: at(0, 13, 15),
      allDay: false,
      color: "#F5A623",
      icon: "UtensilsCrossed",
      completed: false,
      source: "manual",
    },
    {
      id: "e-today-4",
      title: "Deep Work — Nova Development",
      description: "Uninterrupted focus block for the Calendar module.",
      type: "learning",
      category: "Work",
      priority: "high",
      status: "upcoming",
      startDate: at(0, 14, 0),
      endDate: at(0, 16, 0),
      allDay: false,
      color: "#4FD1C5",
      icon: "BrainCircuit",
      completed: false,
      source: "manual",
    },
    {
      id: "e-today-5",
      title: "Gym",
      type: "workout",
      category: "Health",
      priority: "medium",
      status: "upcoming",
      startDate: at(0, 18, 0),
      endDate: at(0, 19, 0),
      allDay: false,
      color: "#6FCF97",
      icon: "Dumbbell",
      completed: false,
      source: "habit",
    },

    // ---- Rest of this week ----
    {
      id: "e-w1",
      title: "Product Demo",
      description: "Walkthrough of the Finance module for stakeholders.",
      type: "meeting",
      category: "Work",
      priority: "high",
      status: "upcoming",
      location: "Conference Room A",
      startDate: at(1, 11, 0),
      endDate: at(1, 12, 0),
      allDay: false,
      attendees: team,
      color: "#7C6CF6",
      icon: "Presentation",
      completed: false,
      source: "manual",
    },
    {
      id: "e-w2",
      title: "Doctor Appointment",
      description: "Annual checkup.",
      type: "health",
      category: "Health",
      priority: "medium",
      status: "upcoming",
      location: "City Clinic",
      startDate: at(2, 16, 30),
      endDate: at(2, 17, 15),
      allDay: false,
      color: "#EF5D6F",
      icon: "Stethoscope",
      completed: false,
      source: "manual",
    },
    {
      id: "e-w3",
      title: "Dinner with Family",
      type: "personal",
      category: "Family",
      priority: "low",
      status: "upcoming",
      startDate: at(2, 20, 0),
      endDate: at(2, 21, 30),
      allDay: false,
      color: "#F5A623",
      icon: "UtensilsCrossed",
      completed: false,
      source: "manual",
    },
    {
      id: "e-w4",
      title: "Reading — Atomic Habits",
      type: "learning",
      category: "Personal",
      priority: "low",
      status: "upcoming",
      startDate: at(3, 21, 0),
      endDate: at(3, 21, 45),
      allDay: false,
      color: "#4FD1C5",
      icon: "BookOpen",
      completed: false,
      source: "habit",
    },
    {
      id: "e-w5",
      title: "Nova Development — Calendar module",
      type: "learning",
      category: "Work",
      priority: "high",
      status: "upcoming",
      startDate: at(4, 10, 0),
      endDate: at(4, 13, 0),
      allDay: false,
      color: "#7C6CF6",
      icon: "BrainCircuit",
      completed: false,
      source: "manual",
    },
    {
      id: "e-w6",
      title: "Electricity Bill Due",
      type: "finance",
      category: "Finance",
      priority: "high",
      status: "upcoming",
      startDate: at(3, 0, 0),
      endDate: at(3, 23, 59),
      allDay: true,
      color: "#F5A623",
      icon: "Zap",
      completed: false,
      source: "finance",
    },
    {
      id: "e-w7",
      title: "Sara's Birthday",
      type: "birthday",
      category: "Social",
      priority: "medium",
      status: "upcoming",
      startDate: at(5, 0, 0),
      endDate: at(5, 23, 59),
      allDay: true,
      color: "#FF8B6B",
      icon: "Cake",
      completed: false,
      source: "manual",
    },

    // ---- Next couple weeks ----
    {
      id: "e-n1",
      title: "Goal Check-in — Run 5K",
      type: "goal",
      category: "Health",
      priority: "medium",
      status: "upcoming",
      startDate: at(7, 7, 0),
      endDate: at(7, 7, 30),
      allDay: false,
      color: "#6FCF97",
      icon: "Target",
      completed: false,
      source: "goal",
    },
    {
      id: "e-n2",
      title: "Flight to Bengaluru",
      type: "travel",
      category: "Personal",
      priority: "high",
      status: "upcoming",
      location: "Terminal 2",
      startDate: at(9, 6, 45),
      endDate: at(9, 9, 0),
      allDay: false,
      color: "#4FD1C5",
      icon: "Plane",
      completed: false,
      source: "manual",
    },
    {
      id: "e-n3",
      title: "Quarterly Investment Review",
      type: "finance",
      category: "Finance",
      priority: "medium",
      status: "upcoming",
      startDate: at(11, 15, 0),
      endDate: at(11, 16, 0),
      allDay: false,
      color: "#F5A623",
      icon: "PiggyBank",
      completed: false,
      source: "finance",
    },
    {
      id: "e-n4",
      title: "Team Standup",
      type: "meeting",
      category: "Work",
      priority: "medium",
      status: "upcoming",
      startDate: at(1, 9, 30),
      endDate: at(1, 9, 50),
      allDay: false,
      attendees: team,
      color: "#7C6CF6",
      icon: "Users",
      completed: false,
      source: "manual",
    },
    {
      id: "e-n5",
      title: "Team Standup",
      type: "meeting",
      category: "Work",
      priority: "medium",
      status: "upcoming",
      startDate: at(2, 9, 30),
      endDate: at(2, 9, 50),
      allDay: false,
      attendees: team,
      color: "#7C6CF6",
      icon: "Users",
      completed: false,
      source: "manual",
    },

    // ---- Past week, for Agenda/history context ----
    {
      id: "e-p1",
      title: "Nova Development — Auth screens",
      type: "learning",
      category: "Work",
      priority: "medium",
      status: "completed",
      startDate: at(-2, 10, 0),
      endDate: at(-2, 12, 0),
      allDay: false,
      color: "#7C6CF6",
      icon: "BrainCircuit",
      completed: true,
      source: "manual",
    },
    {
      id: "e-p2",
      title: "Team Standup",
      type: "meeting",
      category: "Work",
      priority: "low",
      status: "completed",
      startDate: at(-1, 9, 30),
      endDate: at(-1, 9, 50),
      allDay: false,
      attendees: team,
      color: "#7C6CF6",
      icon: "Users",
      completed: true,
      source: "manual",
    },
  ];

  return events;
}
